RUI1001
fcbjimmy/authentication pull request #3
Opened 2022-05-22 11:26 UTC by fcbjimmy

- Merge Authentication and Todo app
- Refactored todo app code

2022-05-22 14:13 UTC, kevin909cty requested changes

2022-05-22 14:13 UTC, kevin909cty commented on src/components/TodoApp/TodoApp.js
> +  function addTodo(newtodo) {
Refactor needed.

2022-05-22 14:13 UTC, kevin909cty commented on src/containers/Index.jsx
> +  console.log({ value });
remove

2022-05-29 12:19 UTC, fcbjimmy commented on src/containers/Index.jsx
> +  console.log({ value });
removed

2022-06-06 14:44 UTC, yutooo5225 commented on src/components/authentication/Welcome.jsx
> +
conside to use CSS:
```
text-transform: capitalize;
```

2022-06-06 14:47 UTC, yutooo5225 commented on src/components/authentication/Login.jsx
> +    setValues({ ...values, showPassword: !values.showPassword });
if you want to change the state depend on *previous state*, use arrow function instead, i.e. `prev => !prev`

2023-01-02 13:04 UTC, merged